#!/usr/bin/env bash

exclude_dirs={.git,expected-result,sample-file}

function replace() {
    is_exact_match=false
    if [ "$1" == "-w" ]; then
        is_exact_match=true
        shift  # Remove the first argument
    fi
    if [ $# -eq 2 ]; then
        old_term="${@:$#-1:1}"  # Second to last argument
        new_term="${!#}"   # Last argument
    else
        echo "[ERROR] At least two arguments are required"
        return 1
    fi
    sed_command="sed -i"
    sed_search_pattern="$old_term"
    if [[ "${BASH_VERSION:0:1}" == "3" ]]; then
        sed_command="$sed_command ''"
    fi
    if [ "$is_exact_match" == true ]; then
        sed_command="$sed_command -E"
        sed_search_pattern="\<$sed_search_pattern\>"
    fi
    for file_path in $(eval "grep -rl $old_term --exclude-dir=$exclude_dirs ."); do
        echo "[DEBUG] Replacing $file_path"
        eval "$sed_command 's/$sed_search_pattern/$new_term/g' $file_path"
    done
    echo "[DEBUG] Done. Replaced '$old_term' with '$new_term'"
}
