#!/usr/bin/env bash

exclude_dirs={.git,expected-result,sample-file}

function replace() {
    # Store last two arguments
    if [ $# -eq 2 ]; then
        old_term="${@:$#-1:1}"  # Second to last argument
        new_term="${!#}"   # Last argument
    else
        echo "Error: At least two arguments are required."
        return 1
    fi
    # TODO
    # if is_exact_match:
    # sed_command = "$sed_command -E"
    # old_term = "\<$old_term\>"
    sed_command="sed -i"
    if [[ "${BASH_VERSION:0:1}" == "3" ]]; then
        sed_command="$sed_command ''"
    fi
    for file_path in $(eval "grep -rl $old_term --exclude-dir=$exclude_dirs ."); do
        echo [DEBUG] Replacing $file_path
        eval "$sed_command 's/$old_term/$new_term/g' $file_path"
    done
    echo "[DEBUG] Done. Replaced '$old_term' with '$new_term'"
}
