#!/usr/bin/env bash

exclude_dirs={.git,expected-result,sample-file}

function replace() {
    old_term=$1
    new_term=$2
    for file_path in $(eval "grep -rl $old_term --exclude-dir=$exclude_dirs ."); do
        echo [DEBUG] Replacing $file_path
        sed_command="sed -i"
        # TODO
        # if is_exact_match:
        # sed_command = "$sed_command -E"
        # term_to_replace = "\<$term_to_replace\>"
        if [[ "${BASH_VERSION:0:1}" == "3" ]]; then
            sed_command = "$sed_command ''"
        fi
        eval "$sed_command 's/$old_term/$new_term/g' $file_path"
    done
    echo "[DEBUG] Done. Replaced '$old_term' with '$new_term'"
}
