#!/usr/bin/env bash

FILE_NAME=foo.txt
FILE_TO_REPLACE=test-files/$FILE_NAME
EXPECTED_DIR=test-files/expected-result

assert_files_match() {
  expected_file=$1
  file_to_compare=$2
  cmp $expected_file $file_to_compare
  if [ $? -ne 0 ]; then
    echo "Error replacing values"
    exit 1
  fi
}

create_file_to_replace() {
  cp test-files/sample-file/$FILE_NAME $FILE_TO_REPLACE
}

# Avoid modifications when running ./replace
restore_this_file() {
  cp /tmp/test-replace .
}

source ./code # To call its functions

cp test-replace /tmp/

# Test case sensitive contains
# The replace must be done.
create_file_to_replace
replace xxx -
restore_this_file
assert_files_match $EXPECTED_DIR/replace-using-contain.txt $FILE_TO_REPLACE
rm $FILE_TO_REPLACE
# The replace must not be done. Upper and lowercase letters does not match
create_file_to_replace
replace xXx -
restore_this_file
assert_files_match test-files/sample-file/$FILE_NAME $FILE_TO_REPLACE
rm $FILE_TO_REPLACE
# The replace must not be done. There is not whole word match
create_file_to_replace
replace -w xxx -
restore_this_file
assert_files_match test-files/sample-file/$FILE_NAME $FILE_TO_REPLACE
rm $FILE_TO_REPLACE
# The replace must be done. There is whole word match
create_file_to_replace
replace -w JohnxxxDoe Charly
restore_this_file
assert_files_match $EXPECTED_DIR/replace-whole-word-match.txt $FILE_TO_REPLACE
rm $FILE_TO_REPLACE
